### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by trvrm** [danvk/pyjsonselect#5]
The current version doesn't quite work with python 3.4, but the changes are minor.

line 99, `ur'...'` needs to become `r'...'`

`basestring` needs to become `str` in a couple of places

and `_forEach(el, node)` needs to become `next(_foreEach(el,node))`

I can put together a patch, if you like, but I'm not sure how to do that in a way that doesn't break Python2.

**Comment by danvk** [comment]
I'd happily accept a patch. It looks like this is a good place to start: https://docs.python.org/3/howto/pyporting.html

**Comment by trvrm** [comment]
I have a working patch, it passes all the nose tests, but *sometimes* fails nosetest3.  This is because dictionary ordering in Python 3 is now non-deterministic (http://stackoverflow.com/questions/14956313/dictionary-ordering-non-deterministic-in-python3), so the expected and actual output in a couple of the tests doesn't always match up.

I can tweak the library to be more predictable, or tweak the tests to be more forgiving - what do you suggest?

**Comment by danvk** [comment]
If the test is failing because it passes in a `dict`, I'd prefer to change it to pass in `collections.OrderedDict`. Where are you seeing the failures?

**Comment by trvrm** [comment]
match_test.py

`eq_(["aMatch", "anotherMatch"], match(".foo", {'foo': "aMatch", 'bar': [ { 'foo': "anotherMatch" } ] }))`

I just ran the test 10 times - it passed 7 times, and the remaining times failed with:

`AssertionError: ['aMatch', 'anotherMatch'] != ['anotherMatch', 'aMatch']`

**Comment by trvrm** [comment]
OrderedDict in the test seems to resolve the problem.

**Comment by danvk** [comment]
See #7 

I'm trying to run the tests with Python3 on Travis, to avoid future regressions, but I'm getting some errors:
https://travis-ci.org/danvk/pyjsonselect/jobs/52224712

mind taking a look?

**Comment by trvrm** [comment]
Sure - I think it's because BaseException.message has been removed from Python 3.

**Comment by danvk** [comment]
Travis tests are passing now. Thanks for fixing this!

**Comment by trvrm** [comment]
Any chance the Python3 compatible version could be pushed to pypi?

**Comment by danvk** [comment]
Sure, I just pushed a 0.2.2 release which includes this fix. Let me know if it works for you!

**Comment by trvrm** [comment]
perfect, thanks!
